### ISSUE TITLE
Make script cross-platform

### ISSUE THREAD

**Issue by bmmpxf** [ConsenSys/mythx-create-accounts#3]
Would be great if this script didn't have a dependency on bash.

Doesn't need to be rewritten in Batch or anything, but maybe a simple Python script.

**Comment by birdofpreyru** [comment]
@bmmpxf It is not really dependent on bash, only on node. The instruction on the first line just allows to call the script as a usual executable on Linux systems, assuming the node is on board. On Windows, if Node is installed, it should be possible to run it as is with `node mythx-create-accounts` command.

**Comment by bmmpxf** [comment]
Oh really? That's great! Thanks, I didn't realize that. Closing.
